jimjam/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('zawadi.urls')),
    url(r'^accounts/',include ('registration.backends.simple.urls')),
    url(r'^logout/$',views.logout, {"next_page": '/'}),
]

zawadi/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^search/', views.search, name='search'),
    url(r'^accounts/edit/',views.edit_profile, name='edit_profile'),
    url(r'^user/(?P<username>\w+)', views.profile, name='profile'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^project/$', views.upload_project, name='upload_project'),
    url(r'^rate/(\d+)',views.vote_project,name = 'rate'),
    url(r'^api/profile/$', views.ProfileList.as_view()),
    url(r'^api/project/$', views.ProjectList.as_view()),
     url(r'^post/(?P<project_id>[0-9]+)/review_design/$',
        views.rate_design, name='rate_design'),
    url(r'^post/(?P<project_id>[0-9]+)/review_usability/$',
        views.rate_usability, name='rate_usability'),
    url(r'^post/(?P<project_id>[0-9]+)/review_content/$',
        views.rate_content, name='rate_content'),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

zawadi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from tinymce.models import HTMLField
from pyuploadcare.dj.models import ImageField
from django.db.models import Avg, Max, Min
from pyuploadcare.dj.forms import FileWidget
from django.conf import settings
import numpy as np

class Profile(models.Model):
    prof_pic = ImageField(blank=True, manual_crop='')
    bio = HTMLField()
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)

    def save_profile(self):
        self.save()
    
    @classmethod
    def search_profile(cls, name):
        profile = Profile.objects.filter(user__username__icontains = name)
        return profile
    
    @classmethod
    def get_by_id(cls, id):
        profile = Profile.objects.get(user = id)
        return profile

    @classmethod
    def filter_by_id(cls, id):
        profile = Profile.objects.filter(user = id).first()
        return profile

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Image(models.Model):
    photo = ImageField(blank=True, manual_crop='')
    profile = models.ForeignKey(User, on_delete=models.CASCADE)
    def save_image(self):
        self.save()
    
    @classmethod
    def get_profile_images(cls, profile):
        images = Image.objects.filter(profile__pk = profile)
        return images

class Project(models.Model):
    '''
    class that contains Project properties
    '''
    title = models.CharField(max_length=40)
    image = ImageField(blank=True, manual_crop='')
    description = models.TextField()
    link = models.URLField(max_length=70)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, default="", blank=True, null=True)
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, default="", blank=True, null=True)
    rating = models.TextField()

    def save_project(self):
        self.save()

    def update_project(self):
        self.update()

    def delete_project(self):
        self.delete()

    @classmethod
    def search_project(cls, title):
        project = cls.objects.filter(title__icontains=title)
        return project

    @classmethod
    def get_posted_projects(cls):
        projects = Project.objects.all()
        return projects

    @classmethod
    def get_projects_on_profile(cls, profile):
        projects = Project.objects.filter(profile__pk=profile)
        return projects

    @classmethod
    def get_project_by_id(cls, id):
        project = Project.objects.filter(user_id=id).all()
        return project

    def average_design(self):
        total_ratings = list(
            map(lambda x: x.rating, self.designrating_set.all()))
        return np.mean(total_ratings)

    def average_usability(self):
        total_ratings = list(
            map(lambda x: x.rating, self.usabilityrating_set.all()))
        return np.mean(total_ratings)

    def average_content(self):
        total_ratings = list(
            map(lambda x: x.rating, self.contentrating_set.all()))
        return np.mean(total_ratings)

    def __str__(self):
        return self.title

class DesignRating(models.Model):
    CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10')
    )
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(Profile)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=CHOICES, default=0)

class UsabilityRating(models.Model):
    CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10')
    )
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(Profile)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=CHOICES, default=0)

class ContentRating(models.Model):
    CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10')
    )
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField(auto_now_add=True,)
    profile = models.ForeignKey(Profile)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=CHOICES, default=0)

zawadi/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from pyuploadcare.dj.forms import FileWidget
from pyuploadcare.dj.models import ImageField

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text = 'Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'image', 'description', 'link')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ['profile']

class ContentForm(forms.ModelForm):
    class Meta:
        model = ContentRating
        fields = ['rating',]

class UsabilityForm(forms.ModelForm):
    class Meta:
        model = UsabilityRating
        fields = ['rating', ]

class DesignForm(forms.ModelForm):
    class Meta:
        model = DesignRating
        fields = ['rating', ]

zawadi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django import forms
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import *

@login_required(login_url='accounts/login')
def home(request):
    projects= Project.get_posted_projects()
    return render(request, 'index.html', {'projects': projects})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your Zawadi account.'
            message = render_to_string('activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user).decode(),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
        return HttpResponse('Confirm your email to complete registration!')
    else:
        form = SignupForm()
    return render(request, 'registration/registration_form.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')
    
def profile(request, username):
    profile = User.objects.get(username=username)
    try:
        profile_details = Profile.get_by_id(profile.id)
    except:
        profile_details = Profile.filter_by_id(profile.id)
    images = Image.get_profile_images(profile.id)
    title = f'@{profile.username} Zawadi'

    return render(request, 'profile/profile.html', {'title':title, 'profile':profile, 'profile_details':profile_details, 'images':images})

@login_required(login_url='/accounts/login')
def upload_image(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            upload = form.save(commit=False)
            upload.profile = request.user
            upload.save()
            return redirect('profile', username=request.user)
    else:
        form = ImageForm()
    
    return render(request, 'profile/upload_image.html', {'form':form})


@login_required(login_url='/accounts/login')
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.user = request.user
            edit.save()
            return redirect('edit_profile')
    else:
        form = ProfileForm()

    return render(request, 'profile/edit_profile.html', {'form':form})

def search(request):
    if 'search' in request.GET and request.GET['search']:
        search_term = request.GET.get('search')
        profiles = Profile.search_profile(search_term)
        projects = Project.search_project(search_term)
        message = f'{search_term}'

        return render(request, 'search.html',{'message':message, 'profiles':profiles, 'projects':projects})
    else:
        message = 'Search for User or Project-name'
        return render(request, 'search.html', {'message':message})

@login_required(login_url='accounts/login/')
def upload_project(request):
    profile = Profile.objects.all()
    for profile in profile:
      if request.method == 'POST':
          form = ProjectForm(request.POST, request.FILES)
          if form.is_valid():
              add=form.save(commit=False)
              add.profile = profile
              add.user = request.user
              add.save()
              return redirect('home')
      else:
          form = ProjectForm()


      return render(request,'upload_projects.html',locals())

@login_required(login_url='accounts/login/')
def vote_project(request, project_id):
   project = Project.objects.get(id=project_id)
   rating = round(((project.design + project.usability + project.content)/3),2)
   if request.method == 'POST':
       form = VoteForm(request.POST)
       if form.is_valid:
           if project.design == 1:
               project.design = int(request.POST['design'])
           else:
               project.design = (project.design + int(request.POST['design']))/2
           if project.usability == 1:
               project.usability = int(request.POST['usability'])
           else:
               project.usability = (project.design + int(request.POST['usability']))/2
           if project.content == 1:
               project.content = int(request.POST['content'])
           else:
               project.content = (project.design + int(request.POST['content']))/2
           project.save()
   else:
       form = VoteForm()
   return render(request,'vote.html',{'form':form,'project':project,'rating':rating})

@login_required(login_url='/login')
def rate_usability(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = UsabilityForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.project = project
            vote.user_name = request.user
            vote.profile = request.user.profile

            vote.save()
        return redirect('home')

    return render(request, 'index.html')

@login_required(login_url='/login')
def rate_design(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = DesignForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.project = project
            vote.user_name = request.user
            vote.profile = request.user.profile

            vote.save()
        return redirect('home')
    else:
        form = DesignForm()

    return render(request, 'index.html',locals())


@login_required(login_url='/login')
def rate_content(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = ContentForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.project = project
            vote.user_name = request.user
            vote.profile = request.user.profile

            vote.save()
        return redirect('home')

    return render(request, 'index.html')

class ProjectList(APIView):
    def get(self, request, format=None):
        all_proj = Project.objects.all()
        serializers = ProjectSerializer(all_proj, many=True)
        return Response(serializers.data)



class ProfileList(APIView):
    def get(self, request, format=None):
        all_profile = Project.objects.all()
        serializers = ProfileSerializer(all_profile, many=True)
        return Response(serializers.data)

zawadi/templates/base.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Home</title>
    {% endif %}

    {% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static 'css/auth.css'%}">
    {% endblock %}
</head>
<body style="background-color:rgba(148, 100, 124,0.9)">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}

    {% block scripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        {% bootstrap_javascript %}
    {% endblock %}
</body> 
</html>

zawadi/templates/index.html
{% extends 'base.html'%}
{% load bootstrap3 %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<br>
<br>

<div style="padding-top: 200px;" class="container">
  <div class="row">
    {% for project in projects %}
        <div class="col-xs-12 col-sm-6 col-md-4 projects">
          <h4 style="font-family: 'Lato', sans-serif;text-align: center;font-size: 20px;color: black;"> {{project.title}} </h4>
        
        <img src="{{project.image.cdn_url}}"  data-toggle="modal" data-target="#exampleModalCenter{{project.id}}" class = "img-responsive project" alt="" style="height:330px;width: 100% !important;position: center;size: cover;">
    

        <!-- Modal -->
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="modal fade" style="width:100% !important;" id="exampleModalCenter{{project.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
              <div class="modal-content" style=" font-family: 'Lato', sans-serif !important;background: rgb(29, 29, 29); color:#d6d3cd;">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalCenterTitle" style="font-size:40px;"><b>{{project.title}}</b></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <img src="{{project.image.cdn_url}}"  class = "img-responsive" alt="" style="height:500px;width: 100%;">
                </div>
                <div class="modal-body">
                  <br>
                  <br>
                  <p style="font-size:22px;padding-right: 70px;"><b>Posted by:</b> {{project.user}}</p>
                  <p style="font-size:22px;padding-right: 70px;"><b>Posted On:</b> {{project.posted_on}}</p>
                  <p style="font-size:22px;padding-right: 70px;"><b>Description:</b> {{project.description}}</p>
                  <form action="">
                    <b style="font-size:22px;" >Link :</b>&nbsp;&nbsp; <a href="{{project.link}}" style="width:100%;height:40px;font-size: 20px;">{{project.link}}</a>
                    <br>
                  </form>
                  <br>
                  <h4 style="color: whitesmoke;text-decoration-line: underline;">Project Rating Criteria</h4>
                  <h5>{{ project.rating.count }} <h5 style="color: green;">a)Design</h5>  average = {{ project.average_design | floatformat }} </h5>

                  <h5>{{ project.rating.count }} <h5 style="color: green;">b)Usability</h5> average = {{ project.average_usability | floatformat }} </h5>

                  <h5>{{ project.rating.count }} <h5 style="color: green;">c)Content</h5>  average = {{ project.average_content | floatformat }}</h5>
                  <br><br>

                  <div class="col-xs-3 col-sm-6 col-md-4 col-lg-4">
                    <h5>a)Rate By Design</h5>



                    <form  action="{%url 'rate_design' project_id=project.id %}" method="POST">
                      {%csrf_token%}
                      {% for field in form %}
                      {% bootstrap_field field %}
                      {% endfor %}
                      <input type="submit" class="btn-md btn btn-success" style="width:50% !important;" value="Rate">
                    </form>
                    <br>
                    <h5>b)Rate By Usability</h5>
                    <form  action="{%url 'rate_usability' project_id=project.id %}" method="POST">
                      {%csrf_token%}
                      {% for field in form %}
                      {% bootstrap_field field %}
                      {% endfor %}
                      <input type="submit" class="btn-md btn btn-success" style="width:50% !important;" value="Rate">
                    </form>

                    <h5>c)Rate By Content</h5>
                    <form  action="{%url 'rate_content' project_id=project.id %}" method="POST" style="width:100%;">
                      {%csrf_token%}
                      {% for field in form %}
                      {% bootstrap_field field %}
                      {% endfor %}
                      <input type="submit" class="btn-md btn btn-success" style="width:50% !important;" value="Rate">
                    </form>
                    <br>


                  </div>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default button" data-dismiss="modal">Close &nbsp;<i class="fas fa-times"></i></button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
      {% endfor %}
    </div>
</div>
    
</div>
  </div>


<style>
  .stars-outer{
    position: relative;
    display: inline-block;
  }
  .stars-inner{
    position: absolute;
    top: 0;
    left: 0;
    white-space: nowrap;
    overflow: hidden;
    width: 0;
  }
  .stars-outer::before {
    content: "\f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005";
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    color: #ccc;
  }
  .stars-inner::before {
    content: "\f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005";
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    color: #f8ce0b !important;
  }
  #id_rating{
    width: 80px !important;
  }
  #id_comment{
    width: 400px !important;
  }
</style>
{% endblock %}
{% block scripts %} {{block.super}}
<script type="text/javascript" src="{%static 'js/ratings.js'%}"></script>
{% endblock %}

zawadi/templates/navbar.html
<nav style="background-color:rgba(97, 47, 72,1)" class="navbar navbar-expand-lg navbar-light fixed-top" id="navMain">
    <div class="container">
        <a style="padding-right: 30px; color: brown;" class="smooth-scroll" href="/"><i class="instagram"><h1>Zawadi</h1></i></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 nav-search">
                        <form class="form-inline my-2 my-lg-0" role="search" action="{% url 'search' %}">
                            <input style="margin-left: 45px;" class="form-control my-2 my-sm-0 search-input" name="search" type="search" placeholder="Search Users" aria-label="Search">
                        </form>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a style="color: brown;" class="nav-link open-nav" href="{% url 'profile' username=user %}"><i class="fa fa-user">{{user}}</i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

zawadi/templates/projects.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load bootstrap4 %}

{% block content %}

 <div class="w3-container">
     <h1 class="text-center">{{project.title}}</h1>
     <hr>

   <div class="w3-row-padding" style="height:500px">
     <img src="{{project.image.cdn_url}}"  class="w3-image" alt=""style="max-height:100%; min-width:100%">
   </div>

   <div class="w3-panel w3-border w3-light-grey w3-round-large">
<h3 class="w3-center w3-serif"> Project Details</h3>
       <hr>


   <div class="w3-row-padding w3-margin">
       <p><strong>Description:  </strong>{{project.description}}</p>
       <p><strong>url:  </strong><a href="{{project.link}}" style="color:blue">{{project.link}}</a></p>

       <div class="w3-row">



  <table class="w3-table w3-striped w3-bordered">
    <tr>
      <th>Design</th>
      <th>Usablity</th>
      <th>Content</th>
    </tr>
    <tr>
      <td>{{project.rating}}</td>
      <td>{{project.rating}}</td>
      <td>{{project.rating}}</td>
    </tr>

  </table>
</div>
  <hr>
   </div>

   <div class="w3-panel w3-leftbar w3-sand  w3-serif">
     <p><strong>Posted </strong>{{project.created_on|timesince}} by {{project.owner.username}}
 </p>
   </div>
       </div>

 </div>

 {% endblock %}

zawadi/templates/search.html
{% extends 'base.html' %}

{% block content %}
<div style="padding: 100px;" class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="font2">Search results for {{message}}</h2>
        </div>
    </div>
    <div class="row">
        {% if profiles %}
            {% for profile in profiles %}
            <div class="col-md-3 home-images search-results">
                {% if profile.prof_pic %}
                <img src="{{profile.prof_pic.cdn_url}}" alt="profile-photo">
                {% else %}
                <img src="/static/img/avatah.png" alt="avatar">
                {% endif %}
                <p class="username">{{profile.user.username}} </p>
                <p><a class="btn btn-primary" href="{% url 'profile' username=profile.user.username %}">View Profile</a></p>
            </div>
            {% endfor %}
        {% else %} 
            <div class="col-md-12 text-center">
                <h4 class="font1">No results for {{message}} </h4>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

zawadi/templates/upload_projects.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load bootstrap4 %}

{% block content %}
<div style="padding-top: 100px;" class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="{% url 'upload_project' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-success btn-lg" value="POST">
            </form>
        </div>
    </div>
</div>
{{ form.media }}
{% endblock %}

zawadi/templates/vote.html
{% extends 'base.html'%}
{% load bootstrap3 %}
{% load bootstrap4 %}

{% block content %}
{{block.super}}

<div  style="">
    <div class="col-md-8">
       <form action="/project/{{project.id}}" method="post" enctype="multipart/form-data">
   {%csrf_token%}
   {% bootstrap_form form%}
    <input type="submit" class="btn btn-success btn-lg" value="Vote">
 </form>
    </div>
</div>
{% endblock %}